In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
# Importing the dataset
dataset = pd.read_csv(r"C:\Users\abdel.aziz.sereme\Desktop\work\udemy\deep learning\Deep_Learning_A_Z\Deep_Learning_A_Z\Volume 1 - Supervised Deep Learning\Part 1 - Artificial Neural Networks (ANN)\Section 4 - Building an ANN\Artificial_Neural_Networks\Churn_Modelling.csv")

In [10]:
len(dataset)

10000

In [12]:
dataset.shape

(10000, 14)

In [11]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [40]:
# Slice and get X and y Values
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [41]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [42]:
#Splitting the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [36]:
X_train

array([ 0.,  1.,  0., ...,  0.,  0.,  1.])

In [37]:
X_test

array([ 1.,  0.,  0., ...,  0.,  1.,  1.])

In [43]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Build the ANN

In [44]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [48]:
#Initialize the AN
classifier = Sequential()

In [49]:
#Add the input layer and first hidden layer
classifier.add(Dense(units = 6, kernel_initializer='uniform', \
                     activation  = 'relu', input_dim = 11 ))

In [50]:
#adding the second hidden layer
classifier.add(Dense(units = 1, kernel_initializer='uniform', \
                    activation = 'relu'))

In [51]:
#Add the output layer
classifier.add(Dense(units = 1, kernel_initializer='uniform', \
                    activation = 'sigmoid'))

In [54]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', \
                  metrics = ['accuracy'])

In [55]:
#Fitting the ANN to training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.5074 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4228 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4134 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4050 - acc: 0.8049
Epoch 5/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3971 - acc: 0.8297
Epoch 6/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3896 - acc: 0.8305
Epoch 7/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3839 - acc: 0.8335
Epoch 8/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.3787 - acc: 0.8420
Epoch 9/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3745 - acc: 0.8447 0s - loss: 0.3723 - acc: 0.84
Epoch 10/100
8000/8000 [==============================] - 1s 105us/step - 

8000/8000 [==============================] - 1s 98us/step - loss: 0.3441 - acc: 0.8595
Epoch 82/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.3439 - acc: 0.8587
Epoch 83/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.3440 - acc: 0.8631
Epoch 84/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.3439 - acc: 0.8581
Epoch 85/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.3441 - acc: 0.8614
Epoch 86/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.3428 - acc: 0.8600
Epoch 87/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.3437 - acc: 0.8599
Epoch 88/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.3430 - acc: 0.8605
Epoch 89/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.3434 - acc: 0.8602
Epoch 90/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.3430 - acc: 0.8620
Epoch 91/1

# Make predictions

In [56]:
#Predicting the test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [59]:
# Make a confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1500   95]
 [ 194  211]]


In [60]:
cm

array([[1500,   95],
       [ 194,  211]], dtype=int64)